### PR TITLE
Support of char escaping in quoteStart context

### PR DESCRIPTION
**Pull request by lpereir4**
In order to support the parsing of a where :
val a = """"\" This highlights the problem. \"""""

### CODE REVIEW

**Comment by tototoshi** [comment]
@lpereir4 
What version are you using?
This has alread fixed in the latest version.
See: https://github.com/tototoshi/scala-csv/issues/32

**Comment by lpereir4** [comment]
@tototoshi I'm using the latest and greatest version (1.2.0)
I added a unit test to the pull request.

Best regards.

**Comment by tototoshi** [comment]
@lpereir4 
Sorry, I missed second commit. Thanks!

**Comment by tototoshi** [comment]
Released as 1.2.1 :rocket:

**Pull request merged**
